spring:
  profiles:
    active: prod
  output:
    ansi:
      enabled: always
  datasource:
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate #Используем hibernate генератор базы данных по аннотациям для валидации
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

db:
  username: ${username.value:postgres}
  password: 1234
  driver: PostgreDriver
  url: postgre:5432
  hosts:
  - localhost
  - 127.0.0.1
  pool:
    size: 10
    timeout: 10
  pools:
    - size: 20
      timeout: 20
    - size: 33
      timeout: 33
  properties:
    first: 123
    second: 11-07-2023
    third.value: Third

#logging:
#  file:
#    name: venidiktov.log
#    path: /